server.port: 8888

spring:
  profiles:
    active: native

spring.cloud.config.server.native.searchLocations: file:${PWD}/configurations
spring.cloud.config.server.encrypt.key: ${CONFIG_SERVER_ENCRYPT_KEY}

spring.security:
    user:
        name: ${CONFIG_SERVER_USER}
        password: ${CONFIG_SERVER_PASSWORD}

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO