server.port: 8888

spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

logging:
  level:
    root: DEBUG

---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/configurations