
spring:
  mvc.format.date-time=iso:
  web.encoding.charset: UTF-8

app:
  rail-data-collector-url: http://rail-data-collector
  rail-data-collector-route-planner-uri: /plan-route
  weather-data-collector-url: http://weather-data-collector
  weather-data-collector-collect-weather-uri: /collect-weather-info
  geocoding-service-url: http://geocoding-service
  delay-data-collector-url: http://delay-data-collector
  delay-data-collector-train-route-uri: /train-routes
  delay-data-collector-train-station-uri: /train-stations
  delay-predictor-service-url: http://delay-predictor-service
  delay-predictor-service-arrival-uri: /prediction/delay/arrival
  delay-predictor-service-departure-uri: /prediction/delay/departure
  geocoding-service-geocoding-uri: /coordinates
  health-check-uri: /actuator/health
  eureka:
    username: '{cipher}26b8501e1e4453ddef760a5c0b0c208e53e2a3e1a560c638e87b5fd2cbabfa73'
    password: '{cipher}40a63f84add14a8be2d18b85ea96fadc07f193e6d519cb98c2f83f9d422b31e9a84d60497d0b6acc8e1567d0a4cf0d63'
    server: localhost
  jwt:
    secret: '{cipher}ec0e48f689aec2a53a829f17342174ddb5c20739dec8740a4ff81a3146dd2d1424fe0136ca891ba8d8a86a1483cf55b083c474808aebd23b8f60a3296f09152b'


eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@${app.eureka.server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: '{cipher}9c1f77865023461b5b0c337a09ef7eb0ebc752aac3bc935c05801b0207306ecf'
  password: '{cipher}ae14a8a44a76b816aff66bfb5be8d7bd7db9876a9b70a08a77d88ff89fa2ac87'

---
spring.config.activate.on-profile: docker

app:
  eureka.server: eureka-server

spring.rabbitmq:
  host: rabbitmq